name: Entalto Aragón
favicon: null
layout_spectrum: 0.46417110809125006
typography_spectrum: 0.6944768682587892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6ba15'
    - '#8f2a20'
    - '#bc6a1d'
    - '#e9a81f'
    - '#a04c10'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5007631641346961
  rhythmicContrast: 0.7032606152351946
purpose: []
