name: Entalto Aragón
favicon: null
layout_spectrum: 0.77635
typography_spectrum: 0.15776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6ba15'
    - '#8f2a20'
    - '#bc6a1d'
    - '#e9a81f'
    - '#a04c10'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.7032606152351946
purpose: []
